name: Monthly Rule Pack Release

on:
  schedule:
    - cron: '0 0 1 * *' # 1st of every month
  workflow_dispatch:

jobs:
  package:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set version and tag
        id: version
        run: |
          YY=$(date +'%y')         # e.g. 25
          MM=$(date +'%m')         # e.g. 06
          VERSION="v$YY.$MM.0"     # e.g. v25.06.0
          TAG_NAME="Rules Bundle ${VERSION}"
          FILE_NAME="rules_bundle_${VERSION}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT

      - name: Determine draft state
        id: draft_state
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "draft=false" >> $GITHUB_OUTPUT
          else
            echo "draft=true" >> $GITHUB_OUTPUT
          fi

      - name: Prepare bundle files
        run: |
          mkdir -p bundle
          cp -r packs/* bundle/

      - name: Create archive
        run: tar -czf "${{ steps.version.outputs.file_name }}.tar.gz" -C bundle .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.tag_name }}
          draft: ${{ steps.draft_state.outputs.draft }}
          generate_release_notes: true
          files: ${{ steps.version.outputs.file_name }}.tar.gz
