name: Validate Rules

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - uses: swatinem/rust-cache@v2

      - name: Install tooka
        run: cargo install tooka

      - name: Find changed .yaml files
        id: yamlfiles
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep '\.yaml$' || true)
          echo "Changed YAML files:"
          echo "$CHANGED_FILES"
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run YAML validation
        id: validate
        run: |
          chmod +x lint_rules.sh
          lint_rules.sh ${{ steps.yamlfiles.outputs.files }}

  
      - name: Comment PR with result
        uses: thollander/actions-comment-pull-request@v3
        if: always()
        with:
          message: ${{ steps.validate.outputs.message }}

