name: Validate Rules

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: swatinem/rust-cache@v2

      - name: Install tooka
        run: cargo install tooka

      - name: Simple validation
        run: |
          set +e
          EXIT_CODE=0
          for file in $(find packs -name "*.yaml"); do
            tooka validate "$file" || EXIT_CODE=1
          done
          exit $EXIT_CODE

      - name: Deep validation
        run: |
          set +e
          EXIT_CODE=0
          for file in $(find packs -name "*.yaml"); do
            tooka validate "$file" --deep || EXIT_CODE=1
          done
          exit $EXIT_CODE

